# Generated by Django 4.2.1 on 2023-05-25 22:44

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', multiselectfield.db.fields.MultiSelectField(choices=[('Cad. Basico', 'Cad. Basico'), ('Pricing', 'Pricing'), ('CRM', 'CRM'), ('PM', 'PM'), ('Operations', 'Operations'), ('DWSYS', 'DWSYS'), ('CLR', 'CLR'), ('DLC', 'DLC'), ('Financial', 'Financial'), ('Chamados', 'Chamados'), ('OKR', 'OKR'), ('All', 'All')], default='All', max_length=200)),
                ('pergunta', models.TextField()),
            ],
        ),
    ]
