# Generated by Django 4.2.1 on 2023-06-24 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pergunta',
            name='respondida',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pergunta',
            name='resposta',
            field=models.TextField(blank=True, null=True),
        ),
    ]
