# Generated by Django 4.2.1 on 2023-06-28 00:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0003_remove_pergunta_resposta_resposta'),
    ]

    operations = [
        migrations.AddField(
            model_name='pergunta',
            name='data_pergunta',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
